export const PRODUCT_LIST_RESQUEST = 'PRODUCT_LIST_RESQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';
export const SET_PRODUCT_LOADING = 'SET_PRODUCT_LOADING';


export const PRODUCT_DETAILS_RESQUEST = 'PRODUCT_DETAILS_RESQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';

export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';


